version: '3'
services:
    scrappr:
        restart: on-failure
        build: .
        command: python3 tse.py
        volumes:
            - .:/app
        depends_on:
            - db
    db:
        restart: always
        container_name: postgres
        image: postgres:latest
        environment:
            - POSTGRES_DB=tse
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - "54322:5432"
        volumes:
            - postgres_data:/var/lib/postgres
volumes:
    .:
    postgres_data:

